#!/usr/bin/env php
<?php

foreach (
    [
        __DIR__ . '/',
        __DIR__ . '/../',
        __DIR__ . '/../../',
        __DIR__ . '/../../../',
    ] as $path
) {
    $file = $path . 'vendor/autoload.php';
    if (file_exists($file)) {
        define('AUTOLOAD', $file);
        break;
    }
}

define('VENDOR', dirname($file) . '/');
unset($path);
unset($file);

require AUTOLOAD;

$path = VENDOR . 'irfantoor/';

if (!is_dir($path)) {
    mkdir($path);
}

$list = [
    'irfantoor/debug' => $path . "debug/src/Debug.php",
    'irfantoor/command'  => $path . "command/src/Command.php",
    'irfantoor/test'  => [
        $path . "test/src/Test.php",
        $path . "test/src/Test/TestCommand.php",
    ],
];

# for classes which can not be directly included by composer
foreach ($list as $package => $files) {
    if (!is_array($files))
        $files = [$files];
    
    foreach ($files as $file) {
        if (file_exists($file)) {
            require $file;
        } else {
            chdir($path);
            system('composer create-project --no-install ' . $package);
            chdir(__DIR__);
        }
    }
}

use IrfanTOOR\Test\TestCommand;

$cmd = new TestCommand(__DIR__ . "/");
$cmd->run();
